### PR TITLE
Updated German translation to have all new fields

### PR DESCRIPTION
**Pull request by kordianbruck**

### CODE REVIEW

**Comment by Ippytraxx** [comment]
Awesome, thanks for updating this!

**Comment by dengelt** [comment]
I have a few things about this translation that I would do differently (and I spotted some mistakes):

1. "Opacity" does not mean "Durchsichtigkeit", in fact that would be the opposite (i.e. transparency).
I would translate "Opacity" with "Deckkraft" or "Deckfähigkeit".

2. "Anmeldung aktuallisieren" contains a typo, it should be "Anmeldung aktualisieren" (delete one L)

3. "In Twitch anmelden" should probably be either "Bei Twitch anmelden", or using an Anglicism "In Twitch einloggen". I would personally prefer the second option, since "anmelden" is a bit ambiguous, it could mean "log in" or "register".

4. "%2.1f stunden." needs to be capitalized, i.e. "%2.1f Stunden."

5. "%ld min." should be "%ld Minuten." for consistency reasons. If we don't use an abbreviation for hours, we also shouldn't use one for minutes.

6. I would change "Beliebte Kanäle, welche du hier sehen möchtest" to either "Favorisierte Kanäle, die du hier sehen möchtest" or "Lieblingskanäle, die du hier sehen möchtest", as "Beliebte Kanäle" does not really imply who likes these channels, they could simply be popular channels.

7. I would change "Versuch eine andere Suche" to "Versuche einen anderen Suchbegriff"

8. Similar to point 3, "Erfolgreich angemeldet!" could be changed to "Erfolgreich eingeloggt!", but since the context is clearer this time, it doesn't matter much.

9. Also similar to points 3 and 8, "Bereits in Twitch angemeldet, neu laden?" could be changed to "Bereits in Twitch eingeloggt, neu laden?".

@kordianbruck let me know what you think.

**Comment by kordianbruck** [comment]
@dengelt I agree with everything. I wouldn't use "einloggen", as it is a anglicism like you said.

Do you want to update the translation?

**Comment by dengelt** [comment]
Alright, I'll get started in a few minutes. I also noticed that the string in point 3 is used as a window caption for a general login/register window, so "anmelden" would be better suited than "einloggen" anyway, since it is ambiguous about which action the user takes.

**Pull request merged**
